import Head from "next/head";
import { useState } from "react";

import { CartModal } from "../components/CartModal";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import { Pokedex } from "../components/Pokedex";

import styles from "../styles/Home.module.scss";

export default function Home() {
  const [isOpen, setIsOpen] = useState<boolean>(false);

  //functions to control the cartModal
  const onCartModalOpen = () => {
    setIsOpen(true);
  };
  const onCartModalClose = () => {
    setIsOpen(false);
  };

  return (
    <>
      <CartModal onClose={onCartModalClose} isOpen={isOpen} />
      <div className={styles.container}>
        <Head>
          <title>E-pokémon</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header onOpen={onCartModalOpen} />
        <section className={styles.main}>
          <h1>Choose your pokémon</h1>
          <Pokedex />
        </section>
      </div>
      <Footer />
    </>
  );
}
