import Head from "next/head";
import React, { useState } from "react";

import { CartModal } from "../components/CartModal";
import { FinishedBuyModal } from "../components/FinishedBuyModal";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import { Pokedex } from "../components/Pokedex";

import styles from "../styles/Home.module.scss";

export default function Home() {
  const [isCartOpen, setIsCartOpen] = useState<boolean>(false);
  const [isFinishedBuyOpen, setIsFinishedBuyOpen] = useState<boolean>(false);
  const [showButtonLoadMore, setShowButtonLoadMore] = useState<boolean>(true);

  /* function to control if the button 'load more' inside Pokedex component will
  be shown. */
  const handlingShowingButtonLoadMore = (value: boolean) => {
    setShowButtonLoadMore(value);
  };

  //functions to control the cartModal
  const onCartModalOpen = () => {
    setIsCartOpen(true);
  };
  const onCartModalClose = () => {
    setIsCartOpen(false);
  };
  //functions to control the FinishedBuyModal
  const onFinishedBuyOpen = () => {
    setIsFinishedBuyOpen(true);
  };
  const onFinishedBuyClose = () => {
    setIsFinishedBuyOpen(false);
  };

  return (
    <>
      <CartModal
        onClose={onCartModalClose}
        isOpen={isCartOpen}
        onFinishedBuyOpen={onFinishedBuyOpen}
      />
      <FinishedBuyModal
        onClose={onFinishedBuyClose}
        isOpen={isFinishedBuyOpen}
      />
      <div className={styles.container}>
        <Head>
          <title>E-pokémon</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header
          onOpen={onCartModalOpen}
          handlingShowingButtonLoadMore={handlingShowingButtonLoadMore}
        />
        <section className={styles.main}>
          <h1>Choose your pokémon</h1>
          <Pokedex showButtonLoadMore={showButtonLoadMore} />
        </section>
      </div>
      <Footer />
    </>
  );
}
